fix build of tests on GHC 9.10 (List)
Data.List from GHC 9.10 now exports a "List" constructor.  The files
test/express-derive.hs and test/name-derive.hs both had constructors named
"List" causing an error.

This change renames both these test constructors to "Lst" instead.

This was the error before this change:

    $ make test-with-ghc-9.10
    ...
    ghc-9.10 -isrc:test:../leancheck/src -O2 -v0 -dynamic test/express-derive.hs && touch test/express-derive
    test/express-derive.hs:11:22: error: [GHC-87543]
        Ambiguous occurrence ‘List’.
        It could refer to
           either ‘Test.List’,
                  imported from ‘Test’ at test/express-derive.hs:6:1-32
                  (and originally defined in ‘GHC.Types’),
               or ‘Main.List’, defined at test/express-derive.hs:11:1.
       |
    11 | data List a  =  a :- List a | Nil deriving (Show, Eq, Typeable)
       |                      ^^^^